language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: amazonse
    token:
      secure: b96411936284395a03d97883fd30af45a2965060
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
