language: java
sudo: false
install: true   
jdk:
  - openjdk8
  
addons:
  sonarcloud:
    organization: "amazonse"
    token:
      secure: "$SONAR_TOKEN"

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
  
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    
notifications:
  slack: my-examples:8M8r1QLTxkacMNjbYEugU5ti
