language: java
sudo: false
install: true
addons:
    sonarqube: true
    
script:
- sonar-scanner -D sonar.host.url=http://192.168.111.148:9000 -D sonar.login=11ef520864c2d8cb262343fd8bfdd1f73cb0dfd8 -X

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
